## https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/bullseye
## docker build -t my_debian_bullseye .
## docker container rm -f debian_bullseye_container && docker run -it --name debian_bullseye_container my_debian_bullseye
FROM scratch
ADD rootfs.tar.xz /
CMD ["bash"]
