## https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/buster/slim
## docker build -t my_debian_buster_slim .
## docker container rm -f debian_buster_slim_container && docker run -it --name debian_buster_slim_container my_debian_buster_slim
FROM scratch
ADD rootfs.tar.xz /
CMD ["bash"]
