## https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/bullseye/slim
## docker build -t my_debian_bullseye_slim .
## docker container rm -f debian_bullseye_slim_container && docker run -it --name debian_bullseye_slim_container my_debian_bullseye_slim
FROM scratch
ADD rootfs.tar.xz /
CMD ["bash"]
