## https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/bookworm/slim
## docker build -t my_debian_bookworm_slim .
## docker container rm -f debian_bookworm_slim_container && docker run -it --name debian_bookworm_slim_container my_debian_bookworm_slim
FROM scratch
ADD rootfs.tar.xz /
CMD ["bash"]
