## https://github.com/alpinelinux/docker-alpine/tree/v3.18/x86_64
## docker build -t my_alpine .
## docker container rm -f alpine_container && docker run -it --name alpine_container my_alpine
FROM scratch
ADD alpine-minirootfs-3.18.0-x86_64.tar.gz /
CMD ["/bin/sh"]