## https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/buster
## docker build -t my_debian_buster .
## docker container rm -f debian_buster_container && docker run -it --name debian_buster_container my_debian_buster
FROM scratch
ADD rootfs.tar.xz /
CMD ["bash"]
