## https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-amd64/bookworm
## docker build -t my_debian_bookworm .
## docker container rm -f debian_bookworm_container && docker run -it --name debian_bookworm_container my_debian_bookworm
FROM scratch
ADD rootfs.tar.xz /
CMD ["bash"]
